### ISSUE TITLE
Add option to put the reference at the start of the quote

### ISSUE THREAD

**Issue by dcpurton** [dcpurton/scripture#10]
There should be an option to put the reference at the start of the quotation, rather than the end.

This should deal sanely with the case where there is a chapter or verse number at the start.

Does it make sense to forbid drop chapters in this case?

**Comment by ReubenM** [comment]
I have a good use case for this. I have a bunch of scripture references in a doc and want to include the passages in an appendix. However when scanning through the appendix to find the matching reference, it is highly preferable to have the references preceding the passage. Especially in cases where it is a long chunk of text.

**Comment by dcpurton** [comment]
@ReubenM I'd be interested in what behaviour you would like to see when the quote starts with it's various internal environments.

I'm on holidays so knowing you would like this gives extra incentive to implement it soonish.

**Comment by ReubenM** [comment]
Right now for the appendix entries I doing this:

```latex
% this doc is using the memoir template

% In preamble:
\newenvironment{appendixscripture}[2]
{
    \noindent\textbf{#1 (#2)}\par\smallskip
    \StrSubstitute{bible.#1}{ }{}[\scripturelabel]
    \begin{adjustwidth}{1.5em}{0pt}
        \begin{scripture}[][noindent,belowskip=16pt]
            \label{\scripturelabel}
}{
        \end{scripture}
    \end{adjustwidth}
}

% in appendix section:
\begin{appendixscripture}{Book 1:1-2}{Translation}
    \vs{1}foo
    \vs{2}bar
\end{appendixscripture}
```

**Comment by dcpurton** [comment]
I see. Putting the reference on a line of its own is pretty easy. I could make some very minor changes to give this a public interface such that you .

I'd also like like to have the option to do something like this:

**Book 1:1–2** Filler text … . ²Filler text … .

such that the first `\ch` and/or `\vs` is automatically suppressed if present. Always putting the reference on  second line in such a case is easy. Looking ahead beyond the beginning of the environment to find out what kind of inner environment is in use and what to do is complicated and maybe exceeds my skill in LaTeX.

In this kind of syntax, I don't know what I'd like to have happen with say the `poetry` environment or `hanging` environment should the quote start with this.

In reality if I were to use this feature in a real world document, I would probably combine with the `compact` option. Although, sometimes useful to have poetry laid out nicely.

Hence why this issue hasn't been addressed.

I see you use a kind of automatic labelling. That's a good idea. I could implement that with a few options to control I reckon.

**Comment by ReubenM** [comment]
For the appendix listing, I'm sort of shooting for a Glossary style of layout where the scripture portion has the left margin increased a little bit. And I do still use the poetry layout when appropriate.

For what you're referring to with the reference inline with the passage, you probably wouldn't want the increased margin. And instead of trying to detect if the environment immediately being starts with poetry, it may be easier to have two options available where one is inline, and the second adds a newline after the reference. And then just trust the the user will set options appropriately for what looks best with the environment used.

So perhaps 3 different options to set? Something like:
1 - "reference/appendix" : Reference is at beginning on it's own line, followed by quote with increased margin. (what I'm currently doing)
2 - "reference/inline" : Reference at beginning, inline with the quote.
3 - "reference/newline" : Reference at beginning on it's own line, no increased margin for quote

When using the first option "reference/appendix", probably offer an additional option associated with it to customize the left margin adjustment for the quote:
"quote/adjustleftmargin" : default maybe something like 2em.

Not sure what is template neutral for adjusting left margin in a way the plays nicely with page breaks and things like twocolumn mode. I believe the "adjustwidth" env I'm using is specific to the memoir template.

**Comment by dcpurton** [comment]
With version 2.0 which should have hit TeXLive and MikTeX by now, the margin handling is much improved. So you should be able to reliably use `leftmargin=0.5em` instead of the `adjuatwidth` environment.

**Comment by dcpurton** [comment]
I think I'd be inclined to do what you are doing with a description environment:

```TeX
\begin{description}
  \item[John 3:16 (NIV)]\strut

    \begin{scripture}
      \vs{16}For God so loved the world that he gave his one and only Son,
      that whoever believes in him shall not perish but have eternal life.
    \end{scripture}

\item[Isaiah 1:2 (NIV)]\strut

  \begin{scripture}
    \begin{poetry}
      \vs{2}Hear me, you heavens! Listen, earth!
      For the \name{Lord} has spoken:

      ‘I reared children and brought them up,
      but they have rebelled against me.
    \end{poetry}
  \end{scripture}
\end{description}
```

**Comment by ReubenM** [comment]
Oh that works perfectly. I hadn't even considered treating it like a list.
